/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { InstantiateMsg, ExecuteMsg, QueryMsg, Addr, PaginatedTokensResponse, Token, TokenInfoResponse } from "./HuahuaFactory.types";
export interface HuahuaFactoryMsg {
  contractAddress: string;
  sender: string;
  createToken: ({
    description,
    subdenom,
    url
  }: {
    description: string;
    subdenom: string;
    url: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  completeBondingCurve: ({
    subdenom
  }: {
    subdenom: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class HuahuaFactoryMsgComposer implements HuahuaFactoryMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createToken = this.createToken.bind(this);
    this.completeBondingCurve = this.completeBondingCurve.bind(this);
  }
  createToken = ({
    description,
    subdenom,
    url
  }: {
    description: string;
    subdenom: string;
    url: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          create_token: {
            description,
            subdenom,
            url
          }
        })),
        funds: _funds
      })
    };
  };
  completeBondingCurve = ({
    subdenom
  }: {
    subdenom: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          complete_bonding_curve: {
            subdenom
          }
        })),
        funds: _funds
      })
    };
  };
}