/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.12.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  fee_collector_address: string;
  subdenom: string;
  token_denom: string;
}
export type ExecuteMsg = {
  buy: {};
} | {
  sell: {};
};
export type QueryMsg = {
  token_price: {};
} | {
  curve_state: {};
} | {
  calculate_buy_amount: {
    token_amount: Coin;
  };
} | {
  calculate_sell_amount: {
    token_amount: Coin;
  };
};
export type Uint128 = string;
export interface Coin {
  amount: Uint128;
  denom: string;
}
export interface CurveState {
  collected: Coin;
  completed: boolean;
  price: Coin;
  sold: Coin;
}